#!/bin/bash

cd ~/kernFiles/$1

for file in *.krn; do

	numS=$(grep '**kern' $file | wc -w)

	for((i=1; i<= numS; i++)); do
		extract -f $i $file |
			sed 's/\\$//g' | 
			humsed '/^[^=]/s/[^0-9.r ]//g' | 
			grep -v -e '^$' -e '^!' -e '^[.]$' -e '^*' |
			sed -e 's/ /:/g' -e 's/=.*/=/g' |
			tr '\n' '-' | 
			tr '=' '\n' |
			sed 's/^-//g' |
			awk NF
	done

done