#!/bin/bash

#cd ~/ResearchSummer2019/$1
cd ./$1
rm -r durations
mkdir durations


for file in *.krn ; do


	sed 's/[[({]//g' $file |
	sed '/^[^0-9].*/d;s/[^0-9.].*//g;' > durations/duration_$file ; done
